sudo: required
#anything we do we need sudo permissions
services:
  - docker
  #will install docker on the container

before_install:
  #a series of steps that need to occur before our test starts
  - docker build -t j-cbblas/docker-react -f Dockerfile.dev .
  #we are tagging the image that gets created just to know its name
  #don't really needed b/c its only used in Travis

script:
  #a series of commands when our test needs to be executed
  #travis watches all these commands
  #anything other than 0 means our code is broken
  - docker run j-cbblas/docker-react npm run test -- --coverage
  #this runs the image createda bove
  #this uses the tag i added to the image created above
  #this overwrites the default command and uses npm run test
  #-- --coverage makes the test finish and close
  #travis waits for the status code 0 to say the test
  #was succesful and completed
